on:
  push:
    branches:
      - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/action-create-release@v1
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2      
      - name: Create Release
        run: |
          npm run init
          npm run build
          npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
